name = "mon-projet-pages"
type = "typescript" # ou "webpack", "typescript", selon ton projet

account_id = "TON_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2025-08-13" # date du jour ou plus récente
route = "" # optionnel si tu déploies sur Pages
zone_id = "" # optionnel si tu déploies sur Pages

[build]
command = "pnpm  build"
cwd = "."
watch_dir = "src"

[vars]
# tes variables d'environnement ici
API_URL = "https://exemple.com/api"
